{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "frontend-demo.serviceAccountName" . }}
  labels:
{{ include "frontend-demo.labels" . | indent 4 }}
{{- end -}}
